FROM nginx:alpine
LABEL for="appotek/treatments:docs"
LABEL project="appotek"
LABEL services="treatments,templates"
LABEL maintainer="Yevhenii Ivanets <evgeniyivanets@gmail.com>"
COPY _site /usr/share/nginx/html
